# Generated by Django 2.2.12 on 2020-08-13 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img_src',
            field=models.CharField(default='https://images.unsplash.com/photo-1464263866732-138a1da44860?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=752&q=80', max_length=500),
            preserve_default=False,
        ),
    ]
