# Generated by Django 2.2.12 on 2020-08-13 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_img_src'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='img_src',
            new_name='image_source',
        ),
    ]
