# Generated by Django 2.2.12 on 2020-08-14 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200813_1225'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='image_source',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='date_created',
            new_name='publish',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='date_modified',
            new_name='update',
        ),
    ]
